### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range

### ISSUE THREAD

**Issue by yassirlaaouissi** [twintproject/twint#933] opened 2020-10-01 20:39 UTC
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
total_tweets = []

    inputfile = open("Zoektermen/keywords.txt", "r")
    for word in inputfile:
        print('\33[33m' + "Het woord is nu: " + word + '\33[0m')
        c = twint.Config()
        c.Search = str(word)
        c.Geo = "52.378909,4.900244,20km"
        c.Store_object = True
        c.Limit = 3200


        # use this for initialscrape
        c.Since = "2020-01-01 00:00:01"
        c.Until = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # use this scrape date for everyday scrape
        # scrapedate = datetime.now() - timedelta(days=1)
        # c.Since = scrapedate.strftime("%Y-%m-%d %H:%M:%S")
        #c.Until = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        twint.run.Search(c)
        tlist = c.search_tweet_list
        total_tweets.append(tlist)
        for tweet in tlist:
            print(str(tweet) + "\n")

    outputfile = open("Output/Twitter/Export_" + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ".csv", "w")
    outputfile.write(tlist)
    return

```
### Description of Issue
> I have a list of keywords which is looped through. Queried on twitter since begin 2020 within a radius of 20km from the city Amsterdam. First keyword gives some results, second keyword only gives the following feedback:

```
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
```
A little backstory: The original API endpoint of twitter went down earlier this week. I pulled an improved version of twint via:
`pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2 `
I am not sure whether this might be causing the CRITICAL error, or its something else. Thanks on forehand for the gentlepeople that are helping me out here :)

### Environment Details
>Using Windows, pycharm community edition, python 3.6

**Comment by yassirlaaouissi** [comment] 2020-10-01 20:40
Test

**Comment by jjvdhoven** [comment] 2020-10-01 20:41
seems kinda sus

**Comment by Jasonnor** [comment] 2020-10-02 08:41
It may be a duplicate of #915

**Comment by yassirlaaouissi** [comment] 2020-10-02 08:45
> It may be a duplicate of #915

@Jasonnor unfortunatly it is not. I encountered the problem in #915 earlier before. And fixed the issue by the following command:
`
pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2`

The API/open source searching endpoint was dead and @yunusemrecatalcam fixed it. After fix other problems occure

**Comment by Him98** [comment] 2020-10-02 18:58
Hey!
I was having the same error:
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915 
For its resolution, I did steps mentioned in #917. But now I am facing this:
`
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
sleeping for 8.0 secs
`  
Can anyone please tell how to resolve this?
Thanks In Advance.

**Comment by yassirlaaouissi** [comment] 2020-10-02 19:07
> 
> 
> Hey!
> I was having the same error:
> CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> For its resolution, I did steps mentioned in #917. But now I am facing this:
> `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> Can anyone please tell how to resolve this?
> Thanks In Advance.

I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam  can look into this, since he is the one who made the initial fix.

**Comment by sukioral** [comment] 2020-10-04 17:34
> > Hey!
> > I was having the same error:
> > CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> > For its resolution, I did steps mentioned in #917. But now I am facing this:
> > `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> > Can anyone please tell how to resolve this?
> > Thanks In Advance.
> 
> I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam can look into this, since he is the one who made the initial fix.

I think it works because you set it to 1 so none of the tweet has been returned?

I followed many posts in #917 but it seems that the problem still not yet be solved. Tried a number of recommended scripts but still got the "sleeping" error.

**Comment by yassirlaaouissi** [comment] 2020-10-04 19:00
> 
> 
> > > Hey!
> > > I was having the same error:
> > > CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> > > For its resolution, I did steps mentioned in #917. But now I am facing this:
> > > `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> > > Can anyone please tell how to resolve this?
> > > Thanks In Advance.
> > 
> > 
> > I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam can look into this, since he is the one who made the initial fix.
> 
> I think it works because you set it to 1 so none of the tweet has been returned?
> 
> I followed many posts in #917 but it seems that the problem still not yet be solved. Tried a number of recommended scripts but still got the "sleeping" error.

Dear @sukioral, I dont know what you mean with the phase: " _I think it works because you set it to 1 so none of the tweet has been returned?" 

If i set c.Limit on one I get plenty of true positive results. When the limit is set on a higher number a get duplicate results. Therefore I think the c.Limit parameter is a bit weird. When I leave the parameter on its default by not giving any variable decleration, I get other gibberish which I dont even bother looking into at this point in my project. Did you apply this command to your project: pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2

**Comment by sukioral** [comment] 2020-10-05 06:40
> > > > Hey!
> > > > I was having the same error:
> > > > CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> > > > For its resolution, I did steps mentioned in #917. But now I am facing this:
> > > > `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> > > > Can anyone please tell how to resolve this?
> > > > Thanks In Advance.
> > > 
> > > 
> > > I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam can look into this, since he is the one who made the initial fix.
> > 
> > 
> > I think it works because you set it to 1 so none of the tweet has been returned?
> > I followed many posts in #917 but it seems that the problem still not yet be solved. Tried a number of recommended scripts but still got the "sleeping" error.
> 
> Dear @sukioral, I dont know what you mean with the phase: " _I think it works because you set it to 1 so none of the tweet has been returned?_"
> 
> If i set c.Limit on one I get plenty of true positive results. When the limit is set on a higher number a get duplicate results. Therefore I think the c.Limit parameter is a bit weird. When I leave the parameter on its default by not giving any variable decleration, I get other gibberish which I dont even bother looking into at this point in my project. Did you apply this command to your project: `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2 `

Sorry if I offended, not my intention. My understanding towards c.Limit is that this limits the numbers of tweet info returned so if set to 1, I thought it will return only 1 tweet maximally. In my trial recently, it returned nothing... When I increase this number, the program just run forever long.

If you don't mind, would you share a small script for fetching the tweets content? I hope there could be at least one solution that works on my side. Thanks.

**Comment by sukioral** [comment] 2020-10-05 06:42
> > > > > Hey!
> > > > > I was having the same error:
> > > > > CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> > > > > For its resolution, I did steps mentioned in #917. But now I am facing this:
> > > > > `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> > > > > Can anyone please tell how to resolve this?
> > > > > Thanks In Advance.
> > > > 
> > > > 
> > > > I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam can look into this, since he is the one who made the initial fix.
> > > 
> > > 
> > > I think it works because you set it to 1 so none of the tweet has been returned?
> > > I followed many posts in #917 but it seems that the problem still not yet be solved. Tried a number of recommended scripts but still got the "sleeping" error.
> > 
> > 
> > Dear @sukioral, I dont know what you mean with the phase: " _I think it works because you set it to 1 so none of the tweet has been returned?_"
> > If i set c.Limit on one I get plenty of true positive results. When the limit is set on a higher number a get duplicate results. Therefore I think the c.Limit parameter is a bit weird. When I leave the parameter on its default by not giving any variable decleration, I get other gibberish which I dont even bother looking into at this point in my project. Did you apply this command to your project: `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2 `
> 
> Sorry if I offended, not my intention. My understanding towards c.Limit is that this limits the numbers of tweet info returned so if set to 1, I thought it will return only 1 tweet maximally. In my trial recently, it returned nothing... When I increase this number, the program just run forever long.
> 
> If you don't mind, would you share a small script for fetching the tweets content? I hope there could be at least one solution that works on my side. Thanks.

I do not know what does this work for, "pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2". Do you mean after updating the twint library using this command could make things work again?

**Comment by HegdeChaitra** [comment] 2020-10-07 05:25
> > > > Hey!
> > > > I was having the same error:
> > > > CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) #915
> > > > For its resolution, I did steps mentioned in #917. But now I am facing this:
> > > > `CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 1.0 secs CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range sleeping for 8.0 secs`
> > > > Can anyone please tell how to resolve this?
> > > > Thanks In Advance.
> > > 
> > > 
> > > I have the same issue on some keywords, for some of the keywords `c.Limit = 1` works. But for others it doesnt. I hope @yunusemrecatalcam can look into this, since he is the one who made the initial fix.
> > 
> > 
> > I think it works because you set it to 1 so none of the tweet has been returned?
> > I followed many posts in #917 but it seems that the problem still not yet be solved. Tried a number of recommended scripts but still got the "sleeping" error.
> 
> Dear @sukioral, I dont know what you mean with the phase: " _I think it works because you set it to 1 so none of the tweet has been returned?_"
> 
> If i set c.Limit on one I get plenty of true positive results. When the limit is set on a higher number a get duplicate results. Therefore I think the c.Limit parameter is a bit weird. When I leave the parameter on its default by not giving any variable decleration, I get other gibberish which I dont even bother looking into at this point in my project. Did you apply this command to your project: `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2`

I am facing the duplicate problem too. When I scrape all tweets for nbcnews with default parameters, it returned 142997 rows out of which only 41 were unique ones. 

Can someone help me with solving the duplicate tweet problem? @yassirlaaouissi any idea on the same?

Twint was installed using [pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2] and below is the code
`c = twint.Config() 
c.Search = "from:@nbcnews" 
c.Store_object = True 
twint.run.Search(c) 
tlist = c.search_tweet_list`

**Comment by yassirlaaouissi** [comment] 2021-01-26 17:36
@Jasonnor @Him98 @HegdeChaitra @sukioral  I have uploaded the result of my project might you guys till have problems with it. Note: My tool consist of various scrapers for different platforms, I have added a technical guidance with code snippets of e.g the Twitter Scraper. Let me know if I can further assist you.

> https://github.com/yassirlaaouissi/IPFIT6_Scraper

**Comment by WokeyLeaks** [comment] 2021-06-15 11:34
got it working with:

**git clone --depth=1 https://github.com/twintproject/twint.git
cd twint
pip3 install . -r requirements.txt**

at that point, you get the 'sleeping' message so

**pip uninstall dataclasses -y**

... then runs fine.

I'm newbie... don't ask me why this works.

**Closed** 2022-01-05 19:43 UTC
