### ISSUE TITLE
[REQUEST] Save Followers with Pandas

### ISSUE THREAD

**Issue by wardnath** [twintproject/twint#173] opened 2018-06-28 13:03 UTC
Non-tweet objects such as followers don't seem compatible with saving to a pandas dataframe

Example:

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twint
>>> c = twint.Config()
>>> c.Username = 'elonmusk'
>>> c.Pandas = True
>>> 
>>> # Run
... twint.run.Followers(c)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/app/vendor/twint/twint/run.py", line 125, in Followers
    run(config)
  File "/opt/app/vendor/twint/twint/run.py", line 117, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/opt/app/vendor/twint/twint/run.py", line 100, in main
    await self.follow()
  File "/opt/app/vendor/twint/twint/run.py", line 54, in follow
    await output.Username(username, self.config, self.conn)
  File "/opt/app/vendor/twint/twint/output.py", line 89, in Username
    _output(username, username, config)
  File "/opt/app/vendor/twint/twint/output.py", line 34, in _output
    panda.update(obj, config.Essid)
  File "/opt/app/vendor/twint/twint/storage/panda.py", line 9, in update
    day = weekday(strftime("%A", localtime(Tweet.datetime)))
AttributeError: 'str' object has no attribute 'datetime'
```

Suggestion:
- In [panda.py update method](https://github.com/twintproject/twint/blob/0683f1c6c61f348cf46d8c999d7486edae235be0/twint/storage/panda.py#L8) add some logic that will determine the type of object being saved (Tweet, User, etc.) and change the dataframe accordingly.

- If the dataframe already has a tweet object and you are adding a different object, raise an error and prompt the user to clear the accumulated data.

**Comment by pielco11** [comment] 2018-06-28 13:41
Thank you so much! I will add this asap

**Comment by pielco11** [comment] 2018-07-01 11:10
![immagine](https://user-images.githubusercontent.com/17363750/42133768-8f0ce934-7d2f-11e8-9efd-4b3bc1774618.png)

It's still in development, but I'm quite sure that this fits our needs, try with `pip install --upgrade -e git+https://github.com/twintproject/twint.git@origin/dev#egg=twint` or just clone **dev** branch and change the name of `twint` (e.g. `mv twint twint_dev`, `import twint_dev ...`)

Returns lists

Give it a try and let me know!

**Comment by derdav3** [comment] 2018-07-24 16:12
@pielco11 I just tried this with `twint.run.Search(c)`, but with `c.Pandas=True` it returns:
`NameError: name 'Pandas' is not defined`
and with `c.Pandas=False` it returns an empty DataFrame...
Is this intended behavior?

**Comment by derdav3** [comment] 2018-07-25 08:32
@pielco11 Sorry I was confused - I installed the package in a notebook, then could import it, but it didn't work... only after restarting the kernel it worked as expected.. thanks for your help!

**Comment by pielco11** [comment] 2018-09-23 15:49
### Get followers with their details and get the dataframe containing those details 
![code](https://user-images.githubusercontent.com/17363750/45929922-8ee1f380-bf58-11e8-97ae-8f5cb39843e6.png)
### Get followers without their details and get the corresponding dataframe
![follow](https://user-images.githubusercontent.com/17363750/45929923-8ee1f380-bf58-11e8-99e2-064c56d56a42.png)
### Get tweets from a user and get the corresponding dataframe
![tweets](https://user-images.githubusercontent.com/17363750/45929924-8ee1f380-bf58-11e8-8066-13c55d1276a3.png)

Closing this since I consider this feature as achieved, in case don't hesitate to comment

**Closed by pielco11** 2018-09-23 15:49 UTC

**Comment by mrdeds** [comment] 2018-09-29 16:51
Just used the last code to get tweets to a dataframe and the dataframe keeps empty:

`df = twint.storage.panda.Tweets_df
>>> df
Empty DataFrame
Columns: []
Index: []`

**Comment by mrdeds** [comment] 2018-09-29 16:57
Tryed the last code for getting tweets from a user and get the corresponding dataframe. but just got an empty Dataframe. I'm using the dev branch

`
>>> df = twint.storage.panda.Tweets_df
>>> df
Empty DataFrame
Columns: []
Index: []
`

**Comment by pielco11** [comment] 2018-09-29 17:00
Sorry, my bad

Fixed now in master branch

**Comment by mrdeds** [comment] 2018-09-30 05:39
great! Thanks!
