### ISSUE TITLE
[QUESTION] sending tweets to Elasticsearch with only python script

### ISSUE THREAD

**Issue by StefanoSetti** [twintproject/twint#154] opened 2018-06-15 16:58 UTC
>I've checked the following:
- [x] Python version is 3.5 or higher.
- [X] Using the latest version of Twint.
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

I'm trying to send tweets from an  python script directly to Elasticsearch because i don't need kebana for what i am doing, but using ```config.Elasticsearch = "localhost:9200"``` brings to me this error: 
```
day = weekday(strftime("%A", localtime(Tweet.datetime)))
NameError: name 'weekday' is not defined
```   
### Python script
```python
import twint

# Set-up TWINW config
config = twint.Config()
config.Username      = "revenantRED"
config.Since         = "2018-06-10"
config.Store_json    = True
config.Elasticsearch = "localhost:9200"

# Start searching
twint.run.Profile(config)
```
what is wrong?

### Environment Details
> Using Fedora 28, executing scripts from terminal, ES is in local

**Comment by haccer** [comment] 2018-06-15 19:58
Hi @StefanoSetti 

I believe this is a bug, I'm going to look into this right now

**Comment by pielco11** [comment] 2018-06-15 23:18
Hmmm also strange to me, fixed removing the function and using the same array. Give it a try `pip3 install --upgrade -e https://github.com/twintproject/twint.git@origin/dev#egg=twint`

**Comment by StefanoSetti** [comment] 2018-06-16 08:13
> Hmmm also strange to me, fixed removing the function and using the same array. Give it a try pip3 
> install --upgrade -e https://github.com/twintproject/twint.git@origin/dev#egg=twint
Is this a work-around? Because i need to export my project in to containers and i would like to have a stable solution to this problem

**Comment by pielco11** [comment] 2018-06-16 09:12
@StefanoSetti Yes, that's a workaround, there are two way: call a function (Pythonic way) and don't; since the issue is calling the function I just moved the code inside the called function into the "mother" function. Others parts of the code (`twint/Pandas.py`) are calling that function and everything works great, so it's quite strange.

Now everything seems to work as expected, no changes for the client side

**Comment by StefanoSetti** [comment] 2018-06-16 09:33
@pielco11 so, this command ```pip3 install --upgrade -e https://github.com/twintproject/twint.git@origin/dev#egg=twint``` is something that i want to do in my container set-up right?

**Comment by StefanoSetti** [comment] 2018-06-16 10:50
@pielco11 OK, thanks for the help
> grazie!

**Comment by pielco11** [comment] 2018-06-16 11:06
No problem :+1: , in case do not hesitate to ask

**Comment by StefanoSetti** [comment] 2018-06-16 11:07
I will, thanks a lot.
That's my first time working with Elasticsearch and twitter, so it will be an interesrting travel.

**Comment by StefanoSetti** [comment] 2018-06-16 11:11
I just did what you say but a new error occurred: ```ModuleNotFoundError: No module named 'MySQLdb'```

**Comment by pielco11** [comment] 2018-06-16 11:13
`pip3 install mysqlclient`

**Comment by StefanoSetti** [comment] 2018-06-16 11:16
after:
>pip3 install mysqlclient
i got this error
```Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v5jtpqne/mysqlclient/```

**Comment by StefanoSetti** [comment] 2018-06-16 11:34
I got a big problem, i still can't manage to install ```pip install mysqlclient``` the error returned is: 
```Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-45_4tg8r/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b2x9tv5e-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-45_4tg8r/mysqlclient/```

and now nothing works with twint, i return the same error as before: ```ModuleNotFoundError: No module named 'MySQLdb'```

**Comment by pielco11** [comment] 2018-06-16 11:40
Ok I removed something around, should work

**Comment by StefanoSetti** [comment] 2018-06-16 11:43
so now i do: ```pip3 install --upgrade twint``` and everything should work, right?

**Comment by pielco11** [comment] 2018-06-16 11:44
Nope, again upgrade from twint.... I tried a could of things and indexing into elasticsearch and I'm not having errors, `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by StefanoSetti** [comment] 2018-06-16 11:57
now it works!
Thank you @pielco11

**Comment by pielco11** [comment] 2018-06-16 12:01
Thank you too and my apologies for the inconvenience

(closing this since everything is working right)

**Closed by pielco11** 2018-06-16 12:01 UTC
Labels: bug
